Download Button name and tooltip added
hashgraph/hedera-mirror-node-explorer pull request #1441
Opened 2024-10-17 20:34 UTC by mariyaraj

Fix for https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1185

2024-10-17 21:15 UTC, ericleponner commented
Please join a snapshot to your PR.

2024-10-17 21:31 UTC, mariyaraj commented
> Please join a snapshot to your PR.

Could you clarify what kind of snapshot you need? I am new here and I am not sure, what should I do?

2024-10-18 09:43 UTC, ericleponner commented
> Could you clarify what kind of snapshot you need? I am new here and I am not sure, what should I do?
#1185 includes two screenshots ; could you include the same screenshots with the visual changes you are proposing.

2024-10-21 22:04 UTC, ericleponner requested changes
#1185 includes two screenshots ; could you include the same screenshots with the visual changes you are proposing.

2024-10-24 18:44 UTC, mariyaraj commented
Here are screenshots after my changes: 
![ButtonDownloadTransactionHistory](https://github.com/user-attachments/assets/efe6cde0-5627-49ad-8b22-563df0db422a)
![UntertitleAdded](https://github.com/user-attachments/assets/62908799-f584-4337-839a-f21b5329c2da)

2024-10-25 10:48 UTC, ericleponner requested changes

2024-10-25 10:48 UTC, ericleponner commented on src/components/DownloadButton.vue
- `Download Transaction History` is long : we should replace it by `Download`.
- `Download Transaction History` is fine for `title` attribute but cannot be hard-coded because `DownloadButton` is re-used in other views and different contexts
   - so title / tooltip must be parameterized by adding a new prop to `DownloadButton` (eg `buttonTitle`)
   - some tooltip text must be defined for other `DownloadButton` usage ; your proposals are welcome
- when window width is small, we should hide `Download`and keep the icon only (as it is today)
   - `Footer` view (line 40) shows how to do that

2024-10-25 10:48 UTC, ericleponner commented on src/components/download/DownloadDialog.vue
`This is useful for record keeping and tax reporting.` is a bit too much specific : remove it.

2024-10-25 10:48 UTC, ericleponner commented on src/components/download/TransactionDownloadDialog.vue
- dialog titles are left-aligned everywhere so keep it left-aligned 
- inline help text should be left-aligned too (we have other dialogs like this)
- remove `This is useful …`
- when possible we try to avoid specific CSS definitions and prefer to use Bulma style classes
    - here you can probably achieve the same visual with `has-text-grey` and `mt-x` classes
    - and remove  `dialog-title-container` and `dialog-subtitle`

2024-10-25 23:04 UTC, mariyaraj commented
@ericleponner Changes committed. Here the screenshots:
![ButtonDownloadTransactionHistory](https://github.com/user-attachments/assets/03f070ce-002d-4a64-a259-b2a72fdafce8)
![DownloadButton](https://github.com/user-attachments/assets/12eca03e-09e7-4c30-b799-7d229cd31beb)
![DownloadDialogScreen](https://github.com/user-attachments/assets/3d4a3794-fbda-42b4-b0be-6ace6debe445)

2025-02-27 17:52 UTC, svienot commented
Rebased on new UI design and adapted to it:
 - the download button does not have any label (per the spec)
 - the download dialog gains a small hint sentence explaining what the action does, so the user can CANCEL if this is not what was expected
 - there is no need for a tooltip on the button, given the above (we avoid profusion of tooltips)
 - replaced the download image by the appropriate Lucide icon

2025-02-27 17:54 UTC, svienot commented
<img width="486" alt="Screenshot 2025-02-27 at 18 15 23" src="https://github.com/user-attachments/assets/8b9ee193-2913-4ded-a218-70c87146cf0d" />

2025-02-28 08:49 UTC, ericleponner approved these changes
Looks good

2025-02-28 08:52 UTC, ericleponner approved these changes

2025-02-28 09:05 UTC, merged