Add support for core-config.json
hashgraph/hedera-mirror-node-explorer pull request #1545
Opened 2024-12-05 20:23 UTC by beeradb

This PR adds support for core.config.json within the mirror node explorer helm chart. 

The default values used were copied from https://github.com/hashgraph/hedera-mirror-node-explorer/blob/main/public/core-config.json

2024-12-06 08:20 UTC, mishomihov00 requested changes

2024-12-06 08:20 UTC, mishomihov00 commented on chart/values.yaml
> +# Add cusom reverse proxy configuration.
A typo I guess?

2024-12-09 07:39 UTC, mishomihov00 approved these changes
LGTM

2024-12-09 19:11 UTC, svienot approved these changes
Looks good to me. Tested locally on minikube.

2024-12-09 19:15 UTC, merged