feat: add link to mirror node data for entities
hashgraph/hedera-mirror-node-explorer pull request #875
Opened 2024-01-30 04:34 UTC by Sheng-Long

**Description**:

**Related issue(s)**: #804 

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-30 18:00 UTC, Sheng-Long commented
Not entirely sure what's going on in the unit tests, will check it out

2024-01-31 15:34 UTC, svienot requested changes
See my couple comments.
Other than that, looks good. This is going to be very useful (for us, to begin with)!

2024-01-31 15:34 UTC, svienot commented on src/components/MirrorLink.vue
> +
I suggest to use the following to make the link less prominent (it is for the advanced user) and also not force the user to navigate back to the explorer page:

```
  <a :href="`${networkUrl}api/v1/${entityUrl}/${loc}`" target="_blank">
      <p class="has-text-right has-text-grey h-is-property-text">Show raw data</p>
  </a>
```

2024-01-31 15:34 UTC, svienot commented on src/components/MirrorLink.vue
> +    const networkUrl = props.network == "mainnet" ?  "https://mainnet-public.mirrornode.hedera.com/" : "https://testnet.mirrornode.hedera.com/"
We need to take care of previewnet as well.

2024-01-31 15:34 UTC, svienot commented on src/components/contract/ContractResult.vue
> +
@Sheng-Long  you may rebase your branch onto main. You will get a small fix which solves such margin discrepancies at the end of the pages.
You can get rid of that workaround `<div>`

2024-01-31 15:34 UTC, svienot commented on src/pages/TopicDetails.vue
> +    <div style="height: 24px" />
You can also get rid of that `<div>` element -- see previous comment.

2024-02-02 17:44 UTC, svienot approved these changes
LG

2024-02-02 17:44 UTC, merged